# Generated by Django 4.0.5 on 2022-06-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0006_alter_projects_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributors',
            name='role',
            field=models.CharField(choices=[('AUTHOR', 'Auteur'), ('CONTRIBUTOR', 'Contributeur')], max_length=11),
        ),
    ]
